### ISSUE TITLE
missing or undocumented support for calling bus.del from a to_delete handler

### ISSUE THREAD

**Issue by tkriplean** [TheInvisibles/statebus#25]
Calling bus.del(key) from a to_delete handler on the server will cause an infinite loop. This isn't surprising as the call to bus.del will end up invoking the to_delete handler again. 

I think to_save handlers get around this problem by providing bus.save.fire(obj). But I can't find an equivalent, such as bus.del.fire(key). 

Test case: 

```
port = 3333
bus = require('statebus/server')({
  port: port
  full_node: true
  client: (client) ->
    client.route_defaults_to(bus)
})

bus('test').to_delete = (key) ->
  console.log 'DELETING', key
  bus.del key # causes infinite loop
  # bus.del.fire key   # doesn't exist!

bus.save 
  key: 'test'
  text: "I'm here!"


setTimeout -> 
  bus.del 'test'
, 1000
```

**Comment by toomim** [comment]
Is there a reason you wanted to call del(key) within to_delete(key)?

I do plan to add an equivalent to fire() for delele. Actually I want to remove fire() in exchange for transaction.done(), which you'd use in both to_save and to_delete.

**Comment by tkriplean** [comment]
I'm trying to call del(key) from within to_delete(key) because I want the default behavior of del(key) to take place. If del(key) is invoked after to_delete(key) runs, then that is the answer to my question!

Here's a scenario: 

A post gets deleted. I want to have a to_delete handler that calls del(pst), but also deletes other associated keyed objects like child points and sliders.

**Comment by toomim** [comment]
Ah, thanks I get it.

Yeah delete() currently calls the to_delete handler, and then deletes the state, and doesn't give you any control over the deletion. I think this is a bug, and in the future we need to make to_delete function like to_save, which lets you decide whether or not to actually modify the state. Thank you for pointing this out!

**Comment by toomim** [comment]
I've made to_delete act like to_save, which solves this problem.
